### ISSUE TITLE
Images having a weird shadow?

### ISSUE THREAD

**Issue by saintly2k** [ithrts/ImoutoIB#102]
Saw this on your Imageboard, and now on mine (after upgrade).
See Screenshot for bug -> https://alex.h33t.moe/f/tozxgdck.png
(had to use another img uploader since github doesnt support file-uploading on falkon browser)

**Comment by ithrts** [comment]
refresh cache, i'm not busting it with parameters at this stage. shift click on the reload button should do it.
what you're seeing is the expanded image with class="dnone", but your stylesheet hasn't been updated either on the server or the cache.

**Comment by saintly2k** [comment]
cloudflare issue
