### ISSUE TITLE
Images over 1mb would give an error.

### ISSUE THREAD

**Issue by Studiozinity** [ithrts/ImoutoIB#116]
Whenever a file over 1mb is uploaded, it would give an error saying '413 Request Entity Too Large', even though I have it at the default 8mb limit. I am using nginx as a server but I don't think it's nginx.

**Comment by ithrts** [comment]
>413 Request Entity Too Large
>I am using nginx as a server but I don't think it's nginx.

https://stackoverflow.com/questions/24306335/413-request-entity-too-large-file-upload-issue

Check nginx or php.ini for a default max file size. It's your server rejecting it.

**Comment by Studiozinity** [comment]
Thank you, now it works
