### ISSUE TITLE
.mp4 files show not supported error

### ISSUE THREAD

**Issue by Studiozinity** [ithrts/ImoutoIB#117]
Whenever I would upload a .mp4 or .webm file. It would show this error:

 **Warning: file_get_contents(): Filename cannot be empty in /var/www/html/includes/filehandler.php on line 95**

Images and .gif files work fine though. It's only happened recently.

**Comment by ithrts** [comment]
Can I ask what is the filename?

Does it work to upload the same file on [3dpd.moe/ib/](https://3dpd.moe/ib/?board=img)?

**Comment by Studiozinity** [comment]
I tried it on 3dpd.moe, it works. it might be because I am running it on tor.

**Comment by Studiozinity** [comment]
update: I've tried apache but does not seem to work either.

**Comment by ithrts** [comment]
Works for me through exit nodes. A random guess if you are hosting it behind a hidden service that tor treats hidden services differently and does not supply a filename for privacy reasons and it might need to be given a substitute name if there is none, i don't know.
(this doesnt really make much sense, but its my best guess).
