### ISSUE TITLE
Issues with minimum character requirements

### ISSUE THREAD

**Issue by GarfieldsPipe** [ithrts/ImoutoIB#123]
1. It shouldn't be possible to post threads with neither an image, nor any text;
![image](https://user-images.githubusercontent.com/66557589/147697182-4e9a7a0e-a6d4-46ed-aa49-97e567e83fb0.png)
When the admin has set `$config['post_body_min'] = 0;` the software should check if the thread OP has a file or not. If it doesn't have a file, then it should at least have 1 character of text. If it has neither, the thread cannot be created.

2. This error message is hardcoded: Gomen nasai... Comment too short. **Min: 10**. Even when you have set the minimum character requirement to, for example, 2. That should be dynamically displayed in the error message.

**Comment by ithrts** [comment]
1. I somewhat considered this, but I figured it's best for any communtiy to discourage just spamming images without any text.
I can add a check for when there is neither text nor files to reject the post.


2. There was no (good) reason for this to be hardcoded. The error function itself was lazily written and should be updated.

**Comment by ithrts** [comment]
https://github.com/ithrts/ImoutoIB/pull/130
