### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by GarfieldsPipe** [ithrts/ImoutoIB#124]
When I enter the wrong captcha, I sometimes get `Notice: Undefined index: captcha_text in /var/www/ImoutoIB/post.php on line 198`

**Comment by ithrts** [comment]
Sometimes?

I've never encountered this error. Any details on what you did when this happened? Imageboard, textboard, OP, Reply?

**Comment by ithrts** [comment]
Was this when you enter a correct captcha, but get a posting error for other reasons and click back and try to post again with the same captcha? The session deletes itself. The code is a bit weird, I can make it so you can use the same captcha *unless* the post went through.

**Comment by ithrts** [comment]
should be fixed
