### ISSUE TITLE
Textboard missing postform

### ISSUE THREAD

**Issue by GarfieldsPipe** [ithrts/ImoutoIB#125]
On a fresh install, the post form seems to be missing on the textboard.
![image](https://user-images.githubusercontent.com/66557589/147697672-0ecdf3d1-82c0-4026-a8a6-28a5b4fde3ad.png)

**Comment by GarfieldsPipe** [comment]
Also getting these errors when opening the Catalog on the textboard:


Warning: include(/footer.php): failed to open stream: No such file or directory in /var/www/ImoutoIB/templates/catalog-txt.php on line 33

Warning: include(): Failed opening '/footer.php' for inclusion (include_path='.:/usr/share/php') in /var/www/ImoutoIB/templates/catalog-txt.php on line 33

**Comment by ithrts** [comment]
Embarassing mistake, I moved the post-form to the bottom of the page but forgot it exits out earlier in the code at zero threads.

Also forgot to fix those includes in particular, but I never checked 0 threads functionality so I missed it.

https://github.com/ithrts/ImoutoIB/pull/126/commits/c95cb054b8df3d8ac4ed9db919a842909779cbd3

This should fix it.
