### ISSUE TITLE
Imageboard-Categories + NSFW Indicators on Frontpage [Pull-Request]

### ISSUE THREAD

**Issue by saintly2k** [ithrts/ImoutoIB#128]
hallo, just worked on it since i missed that feature. some screenshots below. code is in a fork of mine at main. i was confused if i should pull request to master or main, so i just inform you here. demo can be found at [imouto.h33t.moe](https://imouto.h33t.moe) regards, saintly.

![futapa+cats+nsfw](https://user-images.githubusercontent.com/63718132/148338332-e67c144c-2d68-4614-874f-8593ee847c72.png)
![yotsuba-b+cats+nsfw](https://user-images.githubusercontent.com/63718132/148338333-2b57d7b6-3c0a-4f69-9a72-1e2e542e5021.png)
![boards+cats+nsfw](https://user-images.githubusercontent.com/63718132/148338326-d94563f2-0e55-46a6-b263-c68c5b7d688b.png)
![frontpage+cats+nsfw](https://user-images.githubusercontent.com/63718132/148338329-8ec980d0-c52b-4893-b1c1-12a597239b56.png)

**Comment by ithrts** [comment]
Good idea, let's discuss it in the PR.

**Comment by ithrts** [comment]
https://github.com/ithrts/ImoutoIB/pull/129
https://github.com/ithrts/ImoutoIB/pull/133
https://github.com/ithrts/ImoutoIB/pull/136/commits/e545d3e111e99c60d5809e53a5a47018e044459c
