### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function array_key_first() in /home/cscafexy/imouto.h33t.moe/templates/boardlist.html on line 12

### ISSUE THREAD

**Issue by saintly2k** [ithrts/ImoutoIB#47]
hmm... why is this happening?
the site where i need help: https://imouto.h33t.moe
i know you guys dont do qa since you aint gettin paid... **but** plaese help me xd

**Comment by ithrts** [comment]
Are you running PHP 7?

https://www.php.net/manual/en/function.array-key-first.php

**Comment by ithrts** [comment]
Additionally just thought about subdomains, I have no idea if it will work in a subdomain. Leaning towards probably not in regards to the links on the page. Might have to make a function to generate links more dynamically.

**Comment by saintly2k** [comment]
Hey, I have PHP 7.2 running.

About the subdomains, I have moved the source to https://h33t.moe/imouto/ and still get the error.

When I run it on `localhost` it runs perfectly fine, just when I transfer the files to my Apache2 server, it starts erroring... xd

**Comment by ithrts** [comment]
You probably have PHP 7.3+ on your localhost then. The error is telling you it doesn't know what array_key_first is and doesn't know what to do, but on the version of PHP i'm using it's defined by default.
I could probably redefine the functions that use array_key_first/last, but there might be other functions too. I'll just update the requirement to 7.3+

**Comment by saintly2k** [comment]
Yes, you were right. And not only did I have php7.2 on my apache2 server, it was php5 xD and I didn’t even notice
I had some ancient bbs and other software running so I rlly didn’t notice it :^)
I also have a ton of other php stuff runnin on there… so you can image the pain of fixing errors, upgrading etc only to get to php7.3 
thanks, it’s now online: https://imouto.h33t.moe
I left it as the demo is, but I problably will change some things to spice ‘dm up and use this properly. Also, if I find some new good banners, I’ll just do a pull request :^)
