### ISSUE TITLE
(Optional) captcha.php & post.php doesn’t work in PHP 8.0

### ISSUE THREAD

**Issue by saintly2k** [ithrts/ImoutoIB#55]
Captcha doesn’t work. Posting as well.
I disabled the captcha in the config, post.php just gives a white screen.

as I mentioned, it’s optional since I prefer php7.x (and most others too).

**Comment by ithrts** [comment]
Got an error log?

A quick look at your server in the /imouto/ location, you might be missing PHP GD for images which is usually setup with php-common on linux at least. Imagecreatefrompng was undefined from what i could see and posting worked on the textboard with no file.

The subdomain imouto location seems to be working fine, good that I don't need to worry about subdomains. Is that one running on PHP8 as it says in the footer or did you change back to 7.3?

**Comment by saintly2k** [comment]
I used it for a few hours, now I changed it back to 7.3.

**Comment by saintly2k** [comment]
About the Error logs... I don't store the apache2 logs, but I think I saw something in the `default.php` called something like debugging? Well... I'll tell the logs as soon I turned them in apache2 on.

GD: Is enabled & fully working.

**Comment by saintly2k** [comment]
This is the error log I got:
`[Mon Oct 04 19:28:15.826497 2021] [proxy_fcgi:error] [pid 8184] [client 162.158.203.5:28308] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function imagecreatetruecolor() in /var/www/imouto.h33t.moe/includes/captcha.php:17\nStack trace:\n#0 {main}\n  thrown in /var/www/imouto.h33t.moe/includes/captcha.php on line 17', referer: https://imouto.h33t.moe/?board=nsfw`

**Comment by ithrts** [comment]
well for future reference when you see "call to undefined function" it means a dependency is probably not installed (assuming there's no typo in the function). you can google the function and see what php version it requires, and if it needs any extra installation.
i'm gonna stick to what is usually included in the "php-common" linux install though which just installs the most common extensions for php.
