### ISSUE TITLE
GIF autoplayback

### ISSUE THREAD

**Issue by saintly2k** [ithrts/ImoutoIB#56]
I noticed that if you post a GIF, it doesn't automaticly plays as long as you don't click on it and open the media file. I didn't find a setting for that in `default.php` so I was wondering if you could implement it...

**Comment by ithrts** [comment]
i've been meaning to use JS to allow for clicking to display image in the page as is standard for most software, and maybe dragging the image to resize it if its too small/big for reading or whatever

animated gif thumbnails though, this is not possible with GD and i would have to install imagemagick for this, and ffmpeg for thumbnailing videos. i'm lazily using shared hosting and not a vps so i cant install anything.

not a priority, probably wont bother.

**Comment by saintly2k** [comment]
sure :)
