### ISSUE TITLE
Upload .mp3/.mp4?

### ISSUE THREAD

**Issue by saintly2k** [ithrts/ImoutoIB#98]
Tried messing with it. In default.php there are “allowed_ext” defined, however when I try upload, it errors. I also took a look in filehandler.php but I am just too stupid to change smth there on my own. How could I make posting videos, audio etc.?

Regards, saintly.

**Comment by saintly2k** [comment]
ah yes... did another upgrade of versions and now it works fine. thnx!

**Comment by ithrts** [comment]
Yeah unfortunately things are going to keep breaking for a while, I don't worry about changing things in a developer version.
I'm gonna need to rewrite the databse soon so most of it will need to be converted (manually, i'm not writing a script for it i'll just wipe my own board instead) or just wiped.
When I've released 1.0 i'll try hard to avoid such things though to make upgrading a little bit easier.
